Traceback (most recent call last):
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/models/model_state.py", line 27, in load_model
    ckpt = torch.load(file, map_location=lambda storage, loc: storage)
  File "/home/daniel/anaconda3/envs/DeepSSM_SysID/lib/python3.7/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/log/single/toy_lgssm/STORN/model/toy_lgssm_h50_z2_n1_bestModel.ckpt'
Train Epoch: [    0/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 37.766
Train Epoch: [    0/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 34.699	Val Loss: 34.805
Train Epoch: [    1/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 34.696
Train Epoch: [    2/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 32.053
Train Epoch: [    3/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 29.481
Train Epoch: [    4/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 26.975
Train Epoch: [    5/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 24.530
Train Epoch: [    5/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 22.167	Val Loss: 22.195
Train Epoch: [    6/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 22.172
Train Epoch: [    7/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 19.921
Train Epoch: [    8/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 17.795
Train Epoch: [    9/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 15.811
Train Epoch: [   10/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 13.976
Train Epoch: [   10/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 12.299	Val Loss: 12.251
Train Epoch: [   11/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 12.297


-----------------------------------------------------------------------------------------
Exiting from training early
-----------------------------------------------------------------------------------------
Model parameters: 61310
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] on linux
device(type='cpu')
Traceback (most recent call last):
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/daniel/anaconda3/envs/DeepSSM_SysID/lib/python3.7/site-packages/torch/nn/modules/module.py", line 305, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/daniel/anaconda3/envs/DeepSSM_SysID/lib/python3.7/site-packages/torch/nn/modules/module.py", line 202, in _apply
    module._apply(fn)
  File "/home/daniel/anaconda3/envs/DeepSSM_SysID/lib/python3.7/site-packages/torch/nn/modules/module.py", line 245, in _apply
    self._buffers[key] = fn(buf)
  File "/home/daniel/anaconda3/envs/DeepSSM_SysID/lib/python3.7/site-packages/torch/nn/modules/module.py", line 305, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/daniel/anaconda3/envs/DeepSSM_SysID/lib/python3.7/site-packages/torch/cuda/__init__.py", line 192, in _lazy_init
    _check_driver()
  File "/home/daniel/anaconda3/envs/DeepSSM_SysID/lib/python3.7/site-packages/torch/cuda/__init__.py", line 102, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
DynamicModel(
  (normalizer_input): Normalizer1D()
  (normalizer_output): Normalizer1D()
  (m): STORN(
    (phi_y): Sequential(
      (0): Linear(in_features=1, out_features=50, bias=True)
      (1): ReLU()
      (2): Linear(in_features=50, out_features=50, bias=True)
    )
    (phi_u): Sequential(
      (0): Linear(in_features=1, out_features=50, bias=True)
      (1): ReLU()
      (2): Linear(in_features=50, out_features=50, bias=True)
    )
    (phi_z): Sequential(
      (0): Linear(in_features=2, out_features=50, bias=True)
      (1): ReLU()
      (2): Linear(in_features=50, out_features=50, bias=True)
    )
    (enc): Sequential(
      (0): Linear(in_features=50, out_features=50, bias=True)
      (1): ReLU()
      (2): Linear(in_features=50, out_features=50, bias=True)
      (3): ReLU()
    )
    (enc_mean): Sequential(
      (0): Linear(in_features=50, out_features=2, bias=True)
    )
    (enc_logvar): Sequential(
      (0): Linear(in_features=50, out_features=2, bias=True)
      (1): ReLU()
    )
    (prior): Sequential(
      (0): Linear(in_features=50, out_features=50, bias=True)
      (1): ReLU()
      (2): Linear(in_features=50, out_features=50, bias=True)
    )
    (prior_mean): Sequential(
      (0): Linear(in_features=50, out_features=2, bias=True)
    )
    (prior_logvar): Sequential(
      (0): Linear(in_features=50, out_features=2, bias=True)
      (1): ReLU()
    )
    (dec): Sequential(
      (0): Linear(in_features=50, out_features=50, bias=True)
      (1): ReLU()
      (2): Linear(in_features=50, out_features=50, bias=True)
    )
    (dec_mean): Sequential(
      (0): Linear(in_features=50, out_features=1, bias=True)
    )
    (dec_logvar): Sequential(
      (0): Linear(in_features=50, out_features=1, bias=True)
      (1): ReLU()
    )
    (rnn_gen): GRU(100, 50, bias=False)
    (rnn_inf): GRU(50, 50, bias=False)
  )
)
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] on linux
tensor([[[-1.8831,  1.3314, -1.4694,  ...,  0.1990, -1.3169,  1.7266]],

        [[ 1.2198,  1.6492,  2.1869,  ...,  0.2883, -0.5065,  0.9036]],

        [[-1.7435, -2.0661, -1.0814,  ...,  0.3832, -1.9637, -2.2882]],

        ...,

        [[-1.6996,  0.3953, -2.1120,  ..., -1.3503, -1.2966,  1.9326]],

        [[ 2.4223,  2.0943, -1.9830,  ...,  2.4540, -2.1532,  2.0682]],

        [[ 0.9154, -2.0507, -1.6574,  ..., -0.2468, -0.8982,  0.3729]]])
torch.Size([32, 1, 64])
tensor([0.1620])
tensor([-0.0002])
<class 'torch.Tensor'>
Traceback (most recent call last):
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/main_single.py", line 142, in <module>
    run_main_single(options, path_general, file_name_general)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/main_single.py", line 91, in run_main_single
    file_name_general=file_name_general)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/train.py", line 136, in run_train
    time_el = time.time() - start_time
UnboundLocalError: local variable 'start_time' referenced before assignment


-----------------------------------------------------------------------------------------
Exiting from training early
-----------------------------------------------------------------------------------------
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] on linux
tensor([0.1636])
<class 'torch.Tensor'>


-----------------------------------------------------------------------------------------
Exiting from training early
-----------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/pydevd.py", line 2127, in <module>
    main()
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/pydevd.py", line 2118, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/pydevd.py", line 1427, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/main_single.py", line 142, in <module>
    run_main_single(options, path_general, file_name_general)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/main_single.py", line 91, in run_main_single
    file_name_general=file_name_general)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/train.py", line 70, in run_train
    vloss = validate(loader_valid)
UnboundLocalError: local variable 'start_time' referenced before assignment
Traceback (most recent call last):
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/main_single.py", line 142, in <module>
    run_main_single(options, path_general, file_name_general)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/main_single.py", line 95, in run_main_single
    df = test.run_test(options, loaders, df, path_general, file_name_general)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/test.py", line 20, in run_test
    normalizer_input, normalizer_output = compute_normalizer(loaders['train'])
KeyboardInterrupt
Model parameters: 61310
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] on linux
tensor([[[-0.8771,  0.5479, -0.6502,  ...,  1.2748, -2.1234,  0.8264]]],
       grad_fn=<CopySlices>)
<class 'torch.Tensor'>
Traceback (most recent call last):
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
NameError: name 'y_sampel' is not defined
tensor([[[-0.8771,  0.5479, -0.6502,  ...,  1.2748, -2.1234,  0.8264]]])
<class 'torch.Tensor'>
tensor([0.2546])
tensor([7.3196e-05])
tensor([[[-0.8771,  0.5479, -0.6502,  ...,  1.2748, -2.1234,  0.8264]]])
Traceback (most recent call last):
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/main_single.py", line 142, in <module>
    run_main_single(options, path_general, file_name_general)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/main_single.py", line 95, in run_main_single
    df = test.run_test(options, loaders, df, path_general, file_name_general)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/test.py", line 62, in run_test
    y_sample, y_sample_mu, y_sample_sigma = modelstate.model.generate(u_test)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/models/dynamic_model.py", line 70, in generate
    if self.normalizer_output is not None:
KeyboardInterrupt
Train Epoch: [    0/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 37.889
Train Epoch: [    0/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 34.788	Val Loss: 34.773
Train Epoch: [    1/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 34.795
Train Epoch: [    2/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 32.129
Train Epoch: [    3/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 29.519
Train Epoch: [    4/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 27.008
Train Epoch: [    5/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 24.563
Train Epoch: [    5/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 22.194	Val Loss: 22.288
Train Epoch: [    6/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 22.193
Train Epoch: [    7/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 19.955
Train Epoch: [    8/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 17.817
Train Epoch: [    9/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 15.851
Train Epoch: [   10/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 14.021
Train Epoch: [   10/  500], Batch [     1/     1 (100%)]	Learning rate: 1.00e-03	Loss: 12.341	Val Loss: 12.404
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] on linux
torch.Size([32, 2])
2
torch.Size([32, 2])


-----------------------------------------------------------------------------------------
Exiting from training early
-----------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/pydevd.py", line 2127, in <module>
    main()
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/pydevd.py", line 2118, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/pydevd.py", line 1427, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/main_single.py", line 142, in <module>
    run_main_single(options, path_general, file_name_general)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/main_single.py", line 91, in run_main_single
    file_name_general=file_name_general)
  File "/home/daniel/05_PhD/00_Research/01_Projects/03_LearningDynamics/DeepSSM_SysID/train.py", line 70, in run_train
    vloss = validate(loader_valid)
UnboundLocalError: local variable 'start_time' referenced before assignment
